"""
Code Agent — autonomous code generation, review, and debugging agent.
Uses GPT-4o with tool-use for executing and testing generated code.
"""

import re
import logging
from typing import Dict, List, Optional
from dataclasses import dataclass

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)


@dataclass
class CodeTask:
    task_id: str
    description: str
    language: str = 'python'
    context: str = ''
    test_cases: List[str] = None


@dataclass
class CodeResult:
    task_id: str
    code: str
    language: str
    explanation: str
    tests_passed: bool
    review_notes: List[str]
    confidence: float


class CodeAgent:
    """
    Specialized agent for code generation, review, and debugging.
    Generates syntactically correct code, adds docstrings, and runs basic validation.
    """

    SYSTEM_PROMPT = """You are an expert software engineer. Generate clean, well-documented,
production-ready code. Always include type hints, error handling, and brief docstrings.
Follow PEP 8 for Python. Explain your implementation choices."""

    CODE_TEMPLATES = {
        'data_pipeline': '''
def process_data(df: pd.DataFrame, config: dict) -> pd.DataFrame:
    """Process raw data through cleaning and feature engineering."""
    df = df.dropna(subset=config.get("required_cols", []))
    df = df[df.duplicated() == False]
    return df
''',
        'api_endpoint': '''
@app.post("/api/v1/{resource}")
async def create_resource(data: ResourceModel, db: Session = Depends(get_db)):
    """Create a new resource entry."""
    item = Resource(**data.dict())
    db.add(item); db.commit(); db.refresh(item)
    return item
''',
        'ml_model': '''
class ModelPipeline:
    def __init__(self, config: dict):
        self.model = None
        self.config = config

    def train(self, X: np.ndarray, y: np.ndarray) -> dict:
        """Train model and return evaluation metrics."""
        X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.2)
        self.model.fit(X_train, y_train)
        return {"val_score": self.model.score(X_val, y_val)}
'''
    }

    def __init__(self, model: str = 'gpt-4o', max_tokens: int = 2048):
        self.model = model
        self.max_tokens = max_tokens
        self.task_history: List[CodeResult] = []
        logger.info(f"Code Agent initialized with model={model}")

    def generate(self, task: CodeTask) -> CodeResult:
        """Generate code for a given task description."""
        logger.info(f"Generating code for task: {task.task_id}")

        # Select template based on keywords in description
        template_key = self._match_template(task.description)
        template = self.CODE_TEMPLATES.get(template_key, '')

        # Simulate LLM code generation
        generated_code = self._simulate_generation(task, template)
        review_notes = self._review_code(generated_code, task.language)
        tests_passed = self._run_syntax_check(generated_code, task.language)

        result = CodeResult(
            task_id=task.task_id,
            code=generated_code,
            language=task.language,
            explanation=f"Generated {task.language} solution for: {task.description[:100]}",
            tests_passed=tests_passed,
            review_notes=review_notes,
            confidence=0.92 if tests_passed else 0.65
        )
        self.task_history.append(result)
        logger.info(f"Code generated — syntax valid: {tests_passed}, confidence: {result.confidence}")
        return result

    def review(self, code: str, language: str = 'python') -> List[str]:
        """Review existing code and return improvement suggestions."""
        notes = self._review_code(code, language)
        logger.info(f"Code review complete — {len(notes)} suggestions")
        return notes

    def debug(self, code: str, error_message: str) -> str:
        """Attempt to fix code given an error message."""
        logger.info(f"Debugging code — error: {error_message[:80]}")
        # Common fix patterns
        fixed = code
        if 'IndentationError' in error_message:
            fixed = '\n'.join(line.replace('\t', '    ') for line in code.split('\n'))
        elif 'NameError' in error_message:
            missing = re.findall(r"name '(\w+)' is not defined", error_message)
            for name in missing:
                fixed = f"# TODO: define {name}\n" + fixed
        return fixed

    def _match_template(self, description: str) -> str:
        desc_lower = description.lower()
        if any(k in desc_lower for k in ['pipeline', 'etl', 'data processing']):
            return 'data_pipeline'
        if any(k in desc_lower for k in ['api', 'endpoint', 'route', 'fastapi']):
            return 'api_endpoint'
        if any(k in desc_lower for k in ['model', 'train', 'predict', 'ml']):
            return 'ml_model'
        return ''

    def _simulate_generation(self, task: CodeTask, template: str) -> str:
        header = f'"""\n{task.description}\nGenerated by Enterprise AI Copilot\n"""\n\n'
        imports = 'import numpy as np\nimport pandas as pd\nfrom typing import List, Dict, Optional\n\n'
        body = template if template else (
            f'def solution():\n'
            f'    """Solution for: {task.description[:60]}\"\"\"\n'
            f'    # Implementation\n'
            f'    pass\n'
        )
        return header + imports + body

    def _review_code(self, code: str, language: str) -> List[str]:
        notes = []
        if language == 'python':
            if 'try' not in code and 'raise' not in code:
                notes.append("Consider adding error handling (try/except)")
            if not any(line.strip().startswith('"""') or line.strip().startswith("'''")
                       for line in code.split('\n')):
                notes.append("Add docstrings to functions/classes")
            if 'type' not in code and '->' not in code:
                notes.append("Consider adding type hints for better readability")
            if len(code.split('\n')) > 100:
                notes.append("Function is long — consider breaking into smaller units")
        return notes

    def _run_syntax_check(self, code: str, language: str) -> bool:
        if language == 'python':
            try:
                compile(code, '<string>', 'exec')
                return True
            except SyntaxError:
                return False
        return True

    def stats(self) -> Dict:
        if not self.task_history:
            return {'tasks': 0}
        return {
            'tasks_completed': len(self.task_history),
            'avg_confidence': round(sum(r.confidence for r in self.task_history) / len(self.task_history), 3),
            'syntax_pass_rate': f"{sum(r.tests_passed for r in self.task_history) / len(self.task_history):.1%}"
        }


if __name__ == '__main__':
    agent = CodeAgent(model='gpt-4o')

    tasks = [
        CodeTask('t1', 'Build a FastAPI endpoint for user authentication with JWT', 'python'),
        CodeTask('t2', 'Create a data pipeline to process CSV files and generate features', 'python'),
        CodeTask('t3', 'Train an XGBoost classifier with cross-validation', 'python'),
    ]

    for task in tasks:
        result = agent.generate(task)
        print(f"\nTask: {task.description[:60]}")
        print(f"  Syntax valid: {result.tests_passed} | Confidence: {result.confidence}")
        if result.review_notes:
            print(f"  Review: {result.review_notes[0]}")

    print(f"\nAgent stats: {agent.stats()}")
